# Generated by Django 3.0.2 on 2020-01-21 23:21

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('type', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            managers=[
                ('action', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('namespace', models.TextField()),
                ('time_taken', models.IntegerField()),
                ('response_code', models.IntegerField()),
                ('date_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            managers=[
                ('response_time', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('frequency', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('namespace_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='rules.Namespace', verbose_name='namespace_id')),
            ],
            managers=[
                ('rule', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RuleAction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('action_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='rules.Action', verbose_name='action_id')),
                ('rule_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='rules.Rule', verbose_name='rule_id')),
            ],
            managers=[
                ('rule_action', django.db.models.manager.Manager()),
            ],
        ),
    ]
