# Generated by Django 3.0.2 on 2020-01-23 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetricData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=100)),
                ('index', models.CharField(max_length=100)),
                ('metric_value', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('frequency', models.IntegerField()),
                ('rule_condition', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('namespace', models.ForeignKey(default=100, on_delete=django.db.models.deletion.SET_DEFAULT, to='rules.Namespace', verbose_name='namespace')),
            ],
        ),
        migrations.CreateModel(
            name='RuleAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('action', models.ForeignKey(default=100, on_delete=django.db.models.deletion.SET_DEFAULT, to='rules.Action', verbose_name='action_id')),
                ('rule', models.ForeignKey(default=100, on_delete=django.db.models.deletion.SET_DEFAULT, to='rules.Rule', verbose_name='rule_id')),
            ],
        ),
    ]
