# Generated by Django 3.0.2 on 2020-01-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='frequency',
            field=models.CharField(max_length=100),
        ),
    ]
