# Generated by Django 3.0.2 on 2020-01-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='action',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='responsetime',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='rule',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='ruleaction',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='rule',
            name='rule',
            field=models.TextField(default='10>20'),
        ),
    ]
